### ISSUE TITLE
Deploy the new server we're building

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box-address-server#19]

**Comment by ajunge** [comment]
Which new server? 3box-address-server ?

**Comment by oed** [comment]
I think this refers to the ipfs/orbit node. cc @c-castillo

**Comment by c-castillo** [comment]
@ajunge @oed I would close this story. For the IPFS/OrbitDB node we already have another story.

**Comment by ajunge** [comment]
Ok @c-castillo

**Comment by oed** [comment]
Closing this as suggested by @c-castillo
