### ISSUE TITLE
"AccessDeniedAccess Denied" error in Status & FF

### ISSUE THREAD

**Issue by oznekenzo** [uport-project/3box-address-server#37]
@oznekenzo commented on [Fri Oct 26 2018](https://github.com/uport-project/3box-dapp/issues/113)

![Screen_Shot_2018-10-26_at_18.13.54.png](https://images.zenhubusercontent.com/5b86d3797f25530fa3d54999/b1338e01-103d-4693-bbaa-27f3e34f3459)

---

@oznekenzo commented on [Fri Oct 26 2018](https://github.com/uport-project/3box-dapp/issues/113#issuecomment-433473643)

@c-castillo is this a server level error?

**Comment by oed** [comment]
@oznekenzo I don't think this has to do with the address server. It could have something to do with the server hosting the dapp though 🤔

**Comment by michaelsena** [comment]
@c-castillo cc

**Comment by oznekenzo** [comment]
@oed yeah sorry I thought I moved this issue back to the dapp repo

**Comment by oznekenzo** [comment]
Issue moved to [uport-project/3box-dapp #131](https://github.com/uport-project/3box-dapp/issues/131) via [**ZenHub**](https://www.zenhub.com/)
