### ISSUE TITLE
Running from command line + express

### ISSUE THREAD

**Issue by ChrisCates** [uport-project/3box-address-server#42]
I actually, added the option to run the pinning server as a CLI tool here: https://github.com/uport-project/3box-pinning-server/pull/21

However, I'm looking to run the address server locally... So a server would be more ideal.
I'm curious if it's okay if I refactor this to also have the option to be accessible via an express server.

**Comment by c-castillo** [comment]
Hi @ChrisCates thanks for your interest in 3box!
We have plans to replace the address-server in the medium term, and using a more decentralized solution instead. 

We have the address-server on lambda + postgres to avoid users the hassle to run their own. 
However, if you want to run your own for any reason, you should also need to fork the library and we don't recommend that.

**Comment by ChrisCates** [comment]
@c-castillo, thanks for clarifying this!~ Much appreciated.
