### ISSUE TITLE
Research ways to make the hash-server "more decentralized"

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-address-server#6]

**Comment by michaelsena** [comment]
Via Discord:
could the databases be replicated in the future? either continuously, with consensus about writes, or at least snapshotted for transparency? or would this expose private information?
i'm not knocking the approach, i think it's great, just wondering if there's anything that could be done to make people more comfortable about adopting it
either making it fully decentralized, or at least forkable

**Comment by oed** [comment]
Closing this in favor of: https://github.com/uport-project/3box/issues/214
